{
    "openapi": "3.0.1",
    "info": {
        "title": "Criteo API",
        "description": "Criteo API - MarketingSolutions",
        "version": "MCP"
    },
    "servers": [
        {
            "url": "https://api.criteo.com"
        }
    ],
    "paths": {
        "/mcp/advertisers/me": {
            "get": {
                "tags": [
                    "Advertiser"
                ],
                "description": "Fetch the portfolio of Advertisers for this account",
                "operationId": "GetPortfolio",
                "security": [
                    {
                        "oauth": []
                    }
                ]
            }
        },
        "/mcp/marketing-solutions/ad-sets": {
            "patch": {
                "tags": [
                    "Campaign"
                ],
                "description": "Patch a list of AdSets.",
                "operationId": "PatchAdSets",
                "security": [
                    {
                        "oauth": [
                            "MarketingSolutions_Campaign_Manage"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Campaign"
                ],
                "description": "Create the specified ad set",
                "operationId": "CreateAdSet",
                "security": [
                    {
                        "oauth": [
                            "MarketingSolutions_Campaign_Manage"
                        ]
                    }
                ]
            }
        },
        "/mcp/marketing-solutions/ad-sets/{ad-set-id}": {
            "get": {
                "tags": [
                    "Campaign"
                ],
                "description": "Get the data for the specified ad set",
                "operationId": "GetAdSet",
                "security": [
                    {
                        "oauth": [
                            "MarketingSolutions_Campaign_Read"
                        ]
                    }
                ]
            }
        },
        "/mcp/marketing-solutions/ad-sets/{ad-set-id}/audience": {
            "put": {
                "tags": [
                    "Campaign"
                ],
                "description": "Link or unlink an audience with an ad set",
                "operationId": "UpdateAdSetAudience",
                "security": [
                    {
                        "oauth": [
                            "MarketingSolutions_Campaign_Manage"
                        ]
                    }
                ]
            }
        },
        "/mcp/marketing-solutions/ad-sets/search": {
            "post": {
                "tags": [
                    "Campaign"
                ],
                "description": "Search your ad sets",
                "operationId": "SearchAdSets",
                "security": [
                    {
                        "oauth": [
                            "MarketingSolutions_Campaign_Read"
                        ]
                    }
                ]
            }
        },
        "/mcp/marketing-solutions/advertisers/{advertiser-id}/ads": {
            "post": {
                "tags": [
                    "Creative"
                ],
                "description": "Create an Ad",
                "operationId": "CreateAdvertiserAd",
                "security": [
                    {
                        "oauth": [
                            "MarketingSolutions_Creative_Manage"
                        ]
                    }
                ]
            }
        },
        "/mcp/marketing-solutions/advertisers/{advertiser-id}/creatives": {
            "get": {
                "tags": [
                    "Creative"
                ],
                "description": "Get the list of self-services Creatives for a given advertiser",
                "operationId": "GetAdvertiserCreatives",
                "security": [
                    {
                        "oauth": [
                            "MarketingSolutions_Creative_Read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Creative"
                ],
                "description": "Create a Creative",
                "operationId": "CreateAdvertiserCreative",
                "security": [
                    {
                        "oauth": [
                            "MarketingSolutions_Creative_Manage"
                        ]
                    }
                ]
            }
        },
        "/mcp/marketing-solutions/audience-segments/create": {
            "post": {
                "tags": [
                    "Audience"
                ],
                "description": "Creates all segments with a valid configuration, and returns their IDs. For those that cannot be created, one or multiple errors are returned.",
                "operationId": "CreateAudienceSegments",
                "security": [
                    {
                        "oauth": [
                            "MarketingSolutions_Audience_Manage"
                        ]
                    }
                ]
            }
        },
        "/mcp/marketing-solutions/audience-segments/in-market-brands": {
            "get": {
                "tags": [
                    "Audience"
                ],
                "description": "Returns a list with all available in-market brands that can be used to define an in-market segment.",
                "operationId": "GetAudienceSegmentsInMarketBrands",
                "security": [
                    {
                        "oauth": [
                            "MarketingSolutions_Audience_Read"
                        ]
                    }
                ]
            }
        },
        "/mcp/marketing-solutions/audience-segments/in-market-interests": {
            "get": {
                "tags": [
                    "Audience"
                ],
                "description": "Returns a list with all available in-market interests that can be used to define an in-market segment. These in-market interests correspond to the Google product taxonomy.",
                "operationId": "GetAudienceSegmentsInMarketInterests",
                "security": [
                    {
                        "oauth": [
                            "MarketingSolutions_Audience_Read"
                        ]
                    }
                ]
            }
        },
        "/mcp/marketing-solutions/audiences/create": {
            "post": {
                "tags": [
                    "Audience"
                ],
                "description": "Creates all audiences with a valid configuration, and returns their IDs. For those that cannot be created, one or multiple errors are returned.",
                "operationId": "CreateAudiences",
                "security": [
                    {
                        "oauth": [
                            "MarketingSolutions_Audience_Manage"
                        ]
                    }
                ]
            }
        },
        "/mcp/marketing-solutions/audiences/search": {
            "post": {
                "tags": [
                    "Audience"
                ],
                "description": "Returns a list of audiences that match the provided filters. If present, the filters are AND'ed together when applied.",
                "operationId": "SearchAudiences",
                "security": [
                    {
                        "oauth": [
                            "MarketingSolutions_Audience_Read"
                        ]
                    }
                ]
            }
        },
        "/mcp/marketing-solutions/campaigns": {
            "post": {
                "tags": [
                    "Campaign"
                ],
                "description": "Create the specified campaign",
                "operationId": "CreateCampaign",
                "security": [
                    {
                        "oauth": [
                            "MarketingSolutions_Campaign_Manage"
                        ]
                    }
                ]
            }
        },
        "/mcp/marketing-solutions/campaigns/{campaign-id}": {
            "get": {
                "tags": [
                    "Campaign"
                ],
                "description": "Get the data for the specified campaign",
                "operationId": "GetCampaign",
                "security": [
                    {
                        "oauth": [
                            "MarketingSolutions_Campaign_Read"
                        ]
                    }
                ]
            }
        },
        "/mcp/marketing-solutions/campaigns/search": {
            "post": {
                "tags": [
                    "Campaign"
                ],
                "description": "Search your ad campaigns",
                "operationId": "SearchCampaigns",
                "security": [
                    {
                        "oauth": [
                            "MarketingSolutions_Campaign_Read"
                        ]
                    }
                ]
            }
        },
        "/mcp/marketing-solutions/me": {
            "get": {
                "tags": [
                    "Gateway"
                ],
                "description": "Get information about the currently logged application",
                "operationId": "GetCurrentApplication",
                "security": [
                    {
                        "oauth": []
                    }
                ]
            }
        },
        "/mcp/recommendation/search": {
            "post": {
                "tags": [
                    "OnSiteRecommendation"
                ],
                "description": "Retrieves a list of products recommended for the given user. This end point can either rely on a Criteo UserId, or a list of user events to perform the recommendation.",
                "operationId": "SearchRecommendedProducts",
                "security": [
                    {
                        "oauth": [
                            "MarketingSolutions_OnSiteRecommendation_Read"
                        ]
                    }
                ]
            }
        },
        "/mcp/statistics/report": {
            "post": {
                "tags": [
                    "Analytics"
                ],
                "description": "The Statistics API allows measurement and reporting on campaigns using the metrics and dimensions you specify.\n# Query\n\n## AdvertiserIds\n\nIf you do not specify any value for advertiserIds, stats for all advertisers in your portfolio will be returned.\nBe worry of requesting too much data.\n\n## Metrics\nMetrics are created with a common structure, such as: SalesAllPc30d\nThe naming follows the following pattern: `[Measurement][Devices][AttributionModel][Lookb[...]",
                "operationId": "GenerateCampaignStatistics",
                "security": [
                    {
                        "oauth": [
                            "MarketingSolutions_Analytics_Read"
                        ]
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth": {
                "type": "oauth2",
                "flows": {
                    "clientCredentials": {
                        "tokenUrl": "https://api.criteo.com/oauth2/token",
                        "scopes": {}
                    },
                    "authorizationCode": {
                        "authorizationUrl": "https://api.criteo.com/oauth2",
                        "tokenUrl": "https://api.criteo.com/oauth2/token",
                        "scopes": {}
                    }
                }
            }
        }
    },
    "security": [
        {
            "oauth": []
        }
    ],
    "tags": [
        {
            "name": "Advertiser"
        },
        {
            "name": "Analytics"
        },
        {
            "name": "Audience"
        },
        {
            "name": "Campaign"
        },
        {
            "name": "Creative"
        },
        {
            "name": "Gateway"
        },
        {
            "name": "OnSiteRecommendation"
        }
    ],
    "x-samples-languages": [
        "java",
        "python",
        "php",
        "csharp",
        "javascript",
        "curl",
        "ruby"
    ]
}
